version: '3.8'
services:
  open-box:
    image: ghcr.io/sxpizhanglei-pixel/open-box-fnos:latest
    container_name: open-box
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - SECRET=openbox123
    volumes:
      - /vol1/1000/docker/open-box/config:/etc/sing-box
      - /vol1/1000/docker/open-box/ui:/app/ui
