services:
  open-box:
    image: ghcr.io/sxpizhanglei-pixel/open-box-fnos:latest
    container_name: open-box
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Asia/Shanghai
      - SECRET=***
    volumes:
      - ${TRIM_PKGVAR:?}/config:/etc/sing-box
      - ${TRIM_PKGVAR:?}/ui:/app/ui
